baseURL = "https://natanpirard.github.io/"
title = "Grow Through Chess"
theme = "hugo-hero-theme"
defaultContentLanguage = "nl"
defaultContentLanguageInSubdir = false

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/Logo_CL.png"
    mobile_height = "66px"
    mobile_width = "110px"
    desktop = "images/Logo_CL.png"
    desktop_height = "66px"
    desktop_width = "110px"
    alt = "Grow Through Chess"

  [params.homepage_meta_tags]
    meta_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_og_title = "Hugo Hero Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[languages]
  [languages.nl]
    label = "Nederlands"
    locale = "nl-be"
    weight = 1

    [[languages.nl.menu.main]]
      name = "Schaaklessen"
      url = "/schaaklessen/"
      weight = 1

    [[languages.nl.menu.main]]
      name = "Over ons"
      url = "/about/"
      weight = 2

    [[languages.nl.menu.main]]
      name = "Inschrijven"
      url = "/inschrijven/"
      weight = 3

    [[languages.nl.menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 4

  [languages.en]
    label = "English"
    locale = "en-us"
    weight = 2

    [[languages.en.menu.main]]
      name = "Chess Lessons"
      url = "/en/schaaklessen/"
      weight = 1

    [[languages.en.menu.main]]
      name = "About Us"
      url = "/en/about/"
      weight = 2

    [[languages.en.menu.main]]
      name = "Sign Up"
      url = "/en/inschrijven/"
      weight = 3

    [[languages.en.menu.main]]
      name = "Contact"
      url = "/en/contact/"
      weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:contentbasename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
